# -*- coding: utf-8 -*-
"""LLM_Classifier_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WvkRK0FLrbYtuV3lNnHtBlmfLqPvtwFw

# 🤖 LLM Text Classifier - IELTS Essay Scoring

Notebook để train LLM (GPT-2) cho bài toán phân loại chất lượng IELTS essays (0-19 scale)

**Các bước:**
1. Setup môi trường & GPU
2. Upload dữ liệu
3. Preprocessing
4. Training
5. Evaluation & Download model

## 1. Kiểm Tra GPU & Cài Đặt Thư Viện
"""

# Kiểm tra GPU
!nvidia-smi

# Cài đặt thư viện
!pip install -q transformers torch pandas numpy scikit-learn scipy tqdm

# Import libraries
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, AutoConfig, get_linear_schedule_with_warmup
import pandas as pd
import numpy as np
from tqdm import tqdm
from sklearn.metrics import accuracy_score, f1_score
from scipy.stats import pearsonr
import re
import warnings
warnings.filterwarnings('ignore')

print(f"PyTorch: {torch.__version__}")
print(f"CUDA: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")

"""## 2. Upload Dữ Liệu

"""

from google.colab import files

print("Upload train_final.csv:")
uploaded_train = files.upload()

print("\nUpload test_final.csv:")
uploaded_test = files.upload()

print("\n✓ Files uploaded!")

"""## 3. Data Preprocessing

"""

def clean_band_score(band_str):
    """Convert IELTS band to 0-19"""
    try:
        band_str = str(band_str).strip().replace('\n', '').replace('\r', '')
        if '<' in band_str:
            return 3
        match = re.search(r'(\d+\.?\d*)', band_str)
        if match:
            band_score = float(match.group(1))
            return max(0, min(19, int(round((band_score / 9.0) * 19))))
        return 10
    except:
        return 10

def preprocess_data(csv_file):
    df = pd.read_csv(csv_file)
    print(f"  {csv_file}: {len(df)} rows")

    texts = df['essay'].astype(str) if 'essay' in df.columns else df.iloc[:, 0].astype(str)
    scores = df['band'].apply(clean_band_score) if 'band' in df.columns else df.iloc[:, 1].apply(clean_band_score)

    new_df = pd.DataFrame({'text': texts, 'score': scores})
    new_df = new_df[new_df['text'].str.strip() != '']
    new_df = new_df[new_df['text'] != 'nan'].drop_duplicates(subset=['text'])

    print(f"  After cleaning: {len(new_df)} rows, scores {new_df['score'].min()}-{new_df['score'].max()}")
    return new_df

train_df = preprocess_data('train_final.csv')
test_df = preprocess_data('test_final.csv')
print(f"\n✓ Data ready! Train: {len(train_df)}, Test: {len(test_df)}")

"""## 4. Model Definition

"""

class LLMTextClassifier(nn.Module):
    """LLM-based Text Classifier for IELTS Scoring"""

    def __init__(self, model_name, num_labels=20, dropout=0.1):
        super().__init__()

        print(f"Loading {model_name}...")
        self.config = AutoConfig.from_pretrained(model_name)
        self.base_model = AutoModelForCausalLM.from_pretrained(
            model_name,
            torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
        )

        hidden_size = self.config.hidden_size

        # Classification head
        self.dropout = nn.Dropout(dropout)
        self.layer_norm = nn.LayerNorm(hidden_size)
        self.classifier = nn.Sequential(
            nn.Linear(hidden_size, hidden_size // 2),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_size // 2, num_labels)
        )

        self.num_labels = num_labels
        total_params = sum(p.numel() for p in self.parameters())
        print(f"Model loaded: {total_params:,} parameters")

    def forward(self, input_ids, attention_mask, labels=None):
        outputs = self.base_model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            output_hidden_states=True,
        )

        hidden_states = outputs.hidden_states[-1]
        sequence_lengths = attention_mask.sum(dim=1) - 1
        batch_size = hidden_states.shape[0]
        last_hidden = hidden_states[torch.arange(batch_size), sequence_lengths]

        last_hidden = self.layer_norm(last_hidden)
        last_hidden = self.dropout(last_hidden)
        logits = self.classifier(last_hidden)

        loss = None
        if labels is not None:
            loss_fct = nn.CrossEntropyLoss()
            loss = loss_fct(logits, labels)

        return type('Output', (), {'loss': loss, 'logits': logits})()

"""## 5. Dataset Class

"""

class IELTSDataset(Dataset):
    """IELTS Essay Dataset for PyTorch"""

    def __init__(self, texts, labels, tokenizer, max_length=512, with_prompt=False):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.with_prompt = with_prompt

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = str(self.texts[idx])
        label = int(self.labels[idx])

        if self.with_prompt:
            text = f"Rate this IELTS essay quality on a scale from 0 to 19: {text}"

        encoding = self.tokenizer(
            text,
            max_length=self.max_length,
            padding='max_length',
            truncation=True,
            return_tensors='pt'
        )

        return {
            'input_ids': encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'labels': torch.tensor(label, dtype=torch.long)
        }

"""## 6. Training Configuration

Thay đổi các tham số này nếu cần:

"""

# ==================== CẤU HÌNH ====================
MODEL_NAME = 'gpt2'
TRAIN_MODE = 'full'              # ← THAY ĐỔI TỪ 'classifier_only'
WITH_PROMPT = True
BATCH_SIZE = 4
EPOCHS = 8
LEARNING_RATE = 5e-6
MAX_LENGTH = 256
# ==================================================

print("Configuration:")
print(f"  Model: {MODEL_NAME}")
print(f"  Mode: {TRAIN_MODE}")
print(f"  Prompt: {WITH_PROMPT}")
print(f"  Batch: {BATCH_SIZE}")
print(f"  Epochs: {EPOCHS}")

"""## 7. Prepare DataLoaders & Model

"""

# Setup device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# Load tokenizer
print(f"\nLoading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.pad_token_id = tokenizer.eos_token_id

# Create datasets
print("Creating datasets...")
train_dataset = IELTSDataset(
    train_df['text'].tolist(),
    train_df['score'].tolist(),
    tokenizer,
    MAX_LENGTH,
    WITH_PROMPT
)

test_dataset = IELTSDataset(
    test_df['text'].tolist(),
    test_df['score'].tolist(),
    tokenizer,
    MAX_LENGTH,
    WITH_PROMPT
)

# Create data loaders
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

print(f"  Train batches: {len(train_loader)}")
print(f"  Test batches: {len(test_loader)}")

# Create model - FIX: Force float32
print("\nInitializing model...")
model = LLMTextClassifier(MODEL_NAME, num_labels=20)
model = model.to(device).to(torch.float32)  # ← THÊM DÒNG NÀY

# Setup optimizer
if TRAIN_MODE == 'classifier_only':
    print("\nFreezing base model, training classifier only...")
    for param in model.base_model.parameters():
        param.requires_grad = False

    trainable_params = list(model.classifier.parameters()) + list(model.layer_norm.parameters())
    optimizer = torch.optim.AdamW(trainable_params, lr=LEARNING_RATE)
else:
    print("\nTraining full model...")
    optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE)

# Learning rate scheduler
total_steps = len(train_loader) * EPOCHS
scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=int(0.1 * total_steps),
    num_training_steps=total_steps
)

print("\n✓ Setup complete! Ready to train.")

"""## 8. Training Loop

**Chú ý:** Cell này sẽ chạy ~30-45 phút với GPU T4

"""

def evaluate(model, dataloader, device):
    """Evaluate model on test set"""
    model.eval()
    total_loss = 0
    all_preds = []
    all_labels = []

    with torch.no_grad():
        for batch in tqdm(dataloader, desc="Evaluating", leave=False):
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)

            outputs = model(input_ids, attention_mask, labels)
            total_loss += outputs.loss.item()

            preds = torch.argmax(outputs.logits, dim=1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    avg_loss = total_loss / len(dataloader)
    accuracy = accuracy_score(all_labels, all_preds)
    f1 = f1_score(all_labels, all_preds, average='weighted')

    correlation = 0.0
    try:
        correlation, _ = pearsonr(all_labels, all_preds)
    except:
        pass

    return {
        'loss': avg_loss,
        'accuracy': accuracy,
        'f1': f1,
        'correlation': correlation
    }

# Training
print("="*60)
print("TRAINING STARTED")
print("="*60)

best_correlation = -1.0
history = {
    'train_loss': [],
    'test_loss': [],
    'test_acc': [],
    'test_f1': [],
    'test_corr': []
}

for epoch in range(EPOCHS):
    # Training phase
    model.train()
    if TRAIN_MODE == 'classifier_only':
        model.base_model.eval()

    total_loss = 0
    progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{EPOCHS}")

    for batch in progress_bar:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        # Forward pass
        outputs = model(input_ids, attention_mask, labels)
        loss = outputs.loss

        # Backward pass
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        scheduler.step()
        optimizer.zero_grad()

        total_loss += loss.item()
        progress_bar.set_postfix({'loss': f'{loss.item():.4f}'})

    avg_train_loss = total_loss / len(train_loader)

    # Evaluation phase
    eval_results = evaluate(model, test_loader, device)

    # Save history
    history['train_loss'].append(avg_train_loss)
    history['test_loss'].append(eval_results['loss'])
    history['test_acc'].append(eval_results['accuracy'])
    history['test_f1'].append(eval_results['f1'])
    history['test_corr'].append(eval_results['correlation'])

    # Print results
    print(f"\nEpoch {epoch+1}/{EPOCHS} Results:")
    print(f"  Train Loss: {avg_train_loss:.4f}")
    print(f"  Test Loss: {eval_results['loss']:.4f}")
    print(f"  Test Accuracy: {eval_results['accuracy']:.4f}")
    print(f"  Test F1: {eval_results['f1']:.4f}")
    print(f"  Test Correlation: {eval_results['correlation']:.4f}")

    # Save best model
    if eval_results['correlation'] > best_correlation:
        best_correlation = eval_results['correlation']
        print(f"  ✓ New best model! Saving...")
        torch.save(model.state_dict(), 'best_model.pt')

print("\n" + "="*60)
print("TRAINING COMPLETED!")
print(f"Best Test Correlation: {best_correlation:.4f}")
print("="*60)

"""## 9. Plot Training History

"""

import matplotlib.pyplot as plt

fig, axes = plt.subplots(2, 2, figsize=(15, 10))

# Loss
axes[0, 0].plot(history['train_loss'], label='Train Loss', marker='o', color='blue')
axes[0, 0].plot(history['test_loss'], label='Test Loss', marker='o', color='orange')
axes[0, 0].set_xlabel('Epoch')
axes[0, 0].set_ylabel('Loss')
axes[0, 0].set_title('Training & Test Loss')
axes[0, 0].legend()
axes[0, 0].grid(True, alpha=0.3)

# Accuracy
axes[0, 1].plot(history['test_acc'], label='Test Accuracy', marker='o', color='green')
axes[0, 1].set_xlabel('Epoch')
axes[0, 1].set_ylabel('Accuracy')
axes[0, 1].set_title('Test Accuracy')
axes[0, 1].legend()
axes[0, 1].grid(True, alpha=0.3)

# F1 Score
axes[1, 0].plot(history['test_f1'], label='Test F1', marker='o', color='purple')
axes[1, 0].set_xlabel('Epoch')
axes[1, 0].set_ylabel('F1 Score')
axes[1, 0].set_title('Test F1 Score')
axes[1, 0].legend()
axes[1, 0].grid(True, alpha=0.3)

# Correlation
axes[1, 1].plot(history['test_corr'], label='Test Correlation', marker='o', color='red')
axes[1, 1].set_xlabel('Epoch')
axes[1, 1].set_ylabel('Correlation')
axes[1, 1].set_title('Test Correlation')
axes[1, 1].legend()
axes[1, 1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('training_history.png', dpi=300, bbox_inches='tight')
plt.show()

print("Chart saved: training_history.png")

"""## 10. Test Predictions

"""

# Load best model
model.load_state_dict(torch.load('best_model.pt'))
model.eval()

def predict_essay(text, model, tokenizer, device, max_length=512, with_prompt=False):
    """Predict score for an essay"""
    if with_prompt:
        text = f"Rate this IELTS essay quality on a scale from 0 to 19: {text}"

    encoding = tokenizer(
        text,
        max_length=max_length,
        padding='max_length',
        truncation=True,
        return_tensors='pt'
    )

    input_ids = encoding['input_ids'].to(device)
    attention_mask = encoding['attention_mask'].to(device)

    with torch.no_grad():
        outputs = model(input_ids, attention_mask)
        logits = outputs.logits
        pred = torch.argmax(logits, dim=1).item()
        probs = torch.softmax(logits, dim=1).cpu().numpy()[0]

        # Get top 3 predictions
        top3_indices = probs.argsort()[-3:][::-1]
        top3 = [(idx, probs[idx]) for idx in top3_indices]

    return pred, top3, probs

# Test with samples
print("="*60)
print("TEST PREDICTIONS")
print("="*60)

num_samples = min(5, len(test_df))
for i in range(num_samples):
    text = test_df.iloc[i]['text']
    true_score = test_df.iloc[i]['score']
    pred_score, top3, probs = predict_essay(text[:500], model, tokenizer, device, MAX_LENGTH, WITH_PROMPT)

    print(f"\n{'='*60}")
    print(f"Sample {i+1}:")
    print(f"{'='*60}")
    print(f"Text: {text[:150]}...")
    print(f"\nTrue Score: {true_score}")
    print(f"Predicted Score: {pred_score}")
    print(f"Confidence: {probs[pred_score]*100:.2f}%")
    print(f"\nTop 3 Predictions:")
    for score, prob in top3:
        print(f"  Score {score}: {prob*100:.2f}%")

    error = abs(pred_score - true_score)
    print(f"\nAbsolute Error: {error}")

print(f"\n{'='*60}")

"""## 11. Confusion Matrix (Optional)

"""

from sklearn.metrics import confusion_matrix
import seaborn as sns

# Get all predictions
model.eval()
all_preds = []
all_labels = []

print("Generating predictions for confusion matrix...")
with torch.no_grad():
    for batch in tqdm(test_loader):
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(input_ids, attention_mask)
        preds = torch.argmax(outputs.logits, dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

# Create confusion matrix
cm = confusion_matrix(all_labels, all_preds)

# Plot
plt.figure(figsize=(14, 12))
sns.heatmap(cm, annot=False, fmt='d', cmap='Blues', cbar=True,
            xticklabels=range(20), yticklabels=range(20))
plt.xlabel('Predicted Score', fontsize=12)
plt.ylabel('True Score', fontsize=12)
plt.title('Confusion Matrix - IELTS Essay Scoring (0-19)', fontsize=14, pad=20)
plt.savefig('confusion_matrix.png', dpi=300, bbox_inches='tight')
plt.show()

print("\nConfusion matrix saved: confusion_matrix.png")

"""## 12. Error Analysis

"""

# Calculate errors
errors = np.array(all_labels) - np.array(all_preds)
abs_errors = np.abs(errors)

# Statistics
print("="*60)
print("ERROR ANALYSIS")
print("="*60)
print(f"\nMean Absolute Error (MAE): {np.mean(abs_errors):.2f}")
print(f"Median Absolute Error: {np.median(abs_errors):.2f}")
print(f"Max Error: {np.max(abs_errors)}")
print(f"Std Error: {np.std(errors):.2f}")

# Error distribution
print(f"\nError Distribution:")
print(f"  Perfect (error = 0): {np.sum(abs_errors == 0)} samples ({np.sum(abs_errors == 0)/len(abs_errors)*100:.1f}%)")
print(f"  Within ±1: {np.sum(abs_errors <= 1)} samples ({np.sum(abs_errors <= 1)/len(abs_errors)*100:.1f}%)")
print(f"  Within ±2: {np.sum(abs_errors <= 2)} samples ({np.sum(abs_errors <= 2)/len(abs_errors)*100:.1f}%)")
print(f"  Within ±3: {np.sum(abs_errors <= 3)} samples ({np.sum(abs_errors <= 3)/len(abs_errors)*100:.1f}%)")

# Plot error distribution
fig, axes = plt.subplots(1, 2, figsize=(15, 5))

# Histogram of errors
axes[0].hist(errors, bins=30, edgecolor='black', alpha=0.7)
axes[0].axvline(x=0, color='red', linestyle='--', linewidth=2, label='Perfect Prediction')
axes[0].set_xlabel('Prediction Error (True - Predicted)')
axes[0].set_ylabel('Frequency')
axes[0].set_title('Distribution of Prediction Errors')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# Absolute errors
axes[1].hist(abs_errors, bins=20, edgecolor='black', alpha=0.7, color='orange')
axes[1].set_xlabel('Absolute Error')
axes[1].set_ylabel('Frequency')
axes[1].set_title('Distribution of Absolute Errors')
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('error_analysis.png', dpi=300, bbox_inches='tight')
plt.show()

print("\nError analysis saved: error_analysis.png")

"""## 13. Download Files

Download model và các kết quả về máy

"""

from google.colab import files
import json

# Save configuration
config = {
    'model_name': MODEL_NAME,
    'train_mode': TRAIN_MODE,
    'with_prompt': WITH_PROMPT,
    'batch_size': BATCH_SIZE,
    'epochs': EPOCHS,
    'learning_rate': LEARNING_RATE,
    'max_length': MAX_LENGTH,
    'best_correlation': best_correlation,
    'train_samples': len(train_df),
    'test_samples': len(test_df)
}

with open('model_config.json', 'w') as f:
    json.dump(config, f, indent=2)

print("Downloading files...")
print("\nFiles available for download:")
print("  1. best_model.pt (~500MB)")
print("  2. model_config.json")
print("  3. training_history.png")
print("  4. confusion_matrix.png")
print("  5. error_analysis.png")

# Download files
files.download('best_model.pt')
files.download('model_config.json')
files.download('training_history.png')
files.download('confusion_matrix.png')
files.download('error_analysis.png')

print("\n✓ All files downloaded!")

"""## 14. Save to Google Drive (Optional)

Lưu vào Drive để không mất khi session kết thúc

"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Create folder
import os
save_dir = '/content/drive/MyDrive/IELTS_LLM_Classifier'
os.makedirs(save_dir, exist_ok=True)

# Copy files to Drive
!cp best_model.pt "{save_dir}/"
!cp model_config.json "{save_dir}/"
!cp training_history.png "{save_dir}/"
!cp confusion_matrix.png "{save_dir}/"
!cp error_analysis.png "{save_dir}/"

print(f"✓ Files saved to Google Drive: {save_dir}")
print("\nYou can access them later even after this session ends!")

"""## 15. How to Use Trained Model

Code để sử dụng model đã train

"""

"""
CODE MẪU: Sử dụng model trong production

Khi muốn dùng model đã train, chạy code này:
"""

# Load model
import torch
import torch.nn as nn
from transformers import AutoTokenizer, AutoModelForCausalLM, AutoConfig
import json

# Load config
with open('model_config.json', 'r') as f:
    config = json.load(f)

MODEL_NAME = config['model_name']
WITH_PROMPT = config['with_prompt']

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# Recreate model architecture (phải giống như khi train)
model = LLMTextClassifier(MODEL_NAME, num_labels=20)
model.load_state_dict(torch.load('best_model.pt', map_location='cpu'))
model.eval()

# Function to predict
def score_essay(essay_text):
    """
    Score an IELTS essay

    Args:
        essay_text (str): The essay to score

    Returns:
        int: Predicted score (0-19)
        dict: Confidence scores for all classes
    """
    if WITH_PROMPT:
        text = f"Rate this IELTS essay quality on a scale from 0 to 19: {essay_text}"
    else:
        text = essay_text

    encoding = tokenizer(
        text,
        max_length=512,
        padding='max_length',
        truncation=True,
        return_tensors='pt'
    )

    with torch.no_grad():
        outputs = model(encoding['input_ids'], encoding['attention_mask'])
        logits = outputs.logits
        probs = torch.softmax(logits, dim=1).cpu().numpy()[0]
        pred = int(torch.argmax(logits, dim=1).item())

    return pred, {i: float(probs[i]) for i in range(20)}

# Example usage
sample_essay = """
Education is one of the most important aspects of modern society.
A good education provides individuals with the knowledge and skills
necessary to succeed in their careers and contribute to their communities.
"""

predicted_score, confidence = score_essay(sample_essay)
print(f"Predicted IELTS Score: {predicted_score}/19")
print(f"Confidence: {confidence[predicted_score]*100:.2f}%")
print(f"\nTop 3 most likely scores:")
sorted_scores = sorted(confidence.items(), key=lambda x: x[1], reverse=True)[:3]
for score, prob in sorted_scores:
    print(f"  Score {score}: {prob*100:.2f}%")